### ISSUE TITLE
api全部403

### ISSUE THREAD

**Issue by MCBBC** [fly3949/sMusic#2]
我apache环境 访问所有api/get页面的时候都是403，请问怎么办?

**Comment by MCBBC** [comment]
无法登陆无法注册首页获取不到数据

**Comment by MCBBC** [comment]
全部显示 Access denied.

**Comment by fly3949** [comment]
403的话，应该是你本机配置的问题。请检查 Apache 配置文件以及网站权限。
或者尝试新建 phpinfo.php 到网站根目录，看看是否可以访问。

**Comment by MCBBC** [comment]
权限没问题 数据库没问题 phpinfo没问题 伪静态也没问题

**Comment by MCBBC** [comment]
http://music.kiteorg.com/ 这个是地址

**Comment by MCBBC** [comment]
http://music.kiteorg.com/info.php?pass=747396522 php的info

**Comment by fly3949** [comment]
请尝试开启下 Apache 的 pathinfo ：
`AcceptPathInfo On`
（忘记说明了....

**Comment by fly3949** [comment]
刚刚尝试使用全新的系统搭建了 Apache 2.4 + PHP 5.6 的环境，没有出现同样的情况。
如果方便，可以联系一下我的 QQ / Telegram ，我再看看什么情况。

**Comment by fly3949** [comment]
环境问题，需要 pathinfo 支持
