### ISSUE TITLE
用的是什么PHP版本捏，5.6似乎不能正常使用

### ISSUE THREAD

**Issue by ThingOfNull** [fly3949/sMusic#3]
登录时一直显示请稍后，index打开只有三个小点点闪烁。

**Comment by fly3949** [comment]
5.6 理论上可以使用，请 F12 打开浏览器开发者工具，把 Console 里的错误信息贴出来看看。
感觉是伪静态没设置好。

**Comment by ThingOfNull** [comment]
### ====
```
jquery.min.js:4 GET http://127.0.0.1/api/get/totalnum 404 (Not Found)
index.php:1 Failed to load http://127.0.0.1/api/get/totalnum: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 404.
```
====
admin无法登陆，报错
```
2jquery.min.js:4 POST http://127.0.0.1/api/user/loggin 404 (Not Found)
index.php:1 Failed to load http://127.0.0.1/api/user/loggin: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 404.
```

似乎是伪静态的问题了

//已经解决，谢谢
伪静态最后一句改为
`RewriteRule ^(.*)$ index.php?/$1 [L]`即可

**Comment by Nsking-xs** [comment]
谢谢，已经解决。
伪静态最后一句改为
`RewriteRule ^(.*)$ index.php?/$1 [L]`即可

**Comment by ThingOfNull** [comment]
又发现了问题。。
一言API有问题，`以https://api.lwl12.com/music/netease/search?keyword=%E7%88%B1%E6%88%91%E4%B8%AD%E5%8D%8E   `（爱我中华）为例，返回的是空值

**Comment by fly3949** [comment]
本地测试可以啊，有网址可以看一下吗

**Comment by fly3949** [comment]
![](https://i.loli.net/2018/05/24/5b068b57cb7e7.png)
[测试地址](https://music.qz5z.ren/)

**Comment by ThingOfNull** [comment]
![qq 20180527174022](https://user-images.githubusercontent.com/16662311/40584554-3c6d5648-61d5-11e8-9963-5622b1db4746.jpg)

**Comment by fly3949** [comment]
经测试的确是这样的，但是换关键词就可以搜索到了。如“爱我中”，感觉是敏感词的问题。
API 维护者 @liwanglin12

**Comment by fly3949** [comment]
API 问题，建议更换 API 或自行用 METING 搭建。
